files:
  - source: /wiki/**/en.md
    ignore:
      - /wiki/**/img/
      - /wiki/Best_Of/
    translation: /%original_path%/%locale%.md
    languages_mapping:
      locale:
        zh-TW: zh-tw
        zh-CN: zh
